### ISSUE TITLE
java null pointer exception !

### ISSUE THREAD

**Issue by sandeep-v1** [devshawn/kafka-gitops#104]
Did fresh install of kafka-gitops using brew.
`kafka-configs git:(master) ✗ kafka-gitops --version
0.2.14` 

Error :

>  kafka-configs git:(master) ✗ kafka-gitops plan
> Generating execution plan...
> 
> java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
> 	at com.devshawn.kafka.gitops.config.KafkaGitopsConfigLoader.handleAuthentication(KafkaGitopsConfigLoader.java:62)
> 	at com.devshawn.kafka.gitops.config.KafkaGitopsConfigLoader.setConfig(KafkaGitopsConfigLoader.java:41)
> 	at com.devshawn.kafka.gitops.config.KafkaGitopsConfigLoader.load(KafkaGitopsConfigLoader.java:18)
> 	at com.devshawn.kafka.gitops.StateManager.<init>(StateManager.java:63)
> 	at com.devshawn.kafka.gitops.cli.PlanCommand.call(PlanCommand.java:37)
> 	at com.devshawn.kafka.gitops.cli.PlanCommand.call(PlanCommand.java:19)
> 	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
> 	at picocli.CommandLine.access$900(CommandLine.java:145)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
> 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
> 	at picocli.CommandLine.execute(CommandLine.java:1904)
> 	at com.devshawn.kafka.gitops.MainCommand.main(MainCommand.java:76)

Error is coming from ConfigLoader, is there a config.yaml that has to be specified some where ? 
Note : 
JAVA_HOME 
`kafka-configs git:(master) ✗ echo $JAVA_HOME
/opt/homebrew/Cellar/openjdk@17/17.0.13/libexec/openjdk.jdk/Contents/Home`

**Comment by sandeep-v1** [comment]
Just observed it happens only when i set 
KAFKA_SASL_JAAS_PASSWORD 
KAFKA_SASL_JAAS_USERNAME 

By the way i am trying to connect to AWS msk

**Comment by sandeep-v1** [comment]
@devshawn any help here ?
